wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1660124999
    t:
      1:
      - 1
      - 41
      - 55
      - 63
      2:
      - 1
      - 41
      - 55
      - 63
      3:
      - 14
      - 16
      4: 3.8.13
      5: 0.12.21
      8:
      - 5
batch_size:
  desc: null
  value: 64
data_percentage:
  desc: null
  value: 0.01
dataset:
  desc: null
  value: imagenet
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.0001
quantize skip-add:
  desc: null
  value: true
